### ISSUE TITLE
new_meme_request: {}とはいったい・・・うごごご！

### ISSUE THREAD

**Issue by y13i** [greymd/echo-meme#25]
template:[{}とはいったい・・・うごごご！]

reference: https://wikiwiki.jp/ffdic/%E3%82%BB%E3%83%AA%E3%83%95/%E3%80%90%E7%84%A1%E3%81%A8%E3%81%AF%E3%81%84%E3%81%A3%E3%81%9F%E3%81%84%E3%83%BB%E3%83%BB%E3%83%BB%E3%81%86%E3%81%94%E3%81%94%E3%81%94%EF%BC%81%E3%80%91

**Comment by greymd** [comment]
THIS COMMENT IS POSTED BY BOT -- [{}とはいったい・・・うごごご！] is imported. You rocked it!
