### ISSUE TITLE
new_meme_request:俺、{}（｀ェ´）ﾋﾟｬｰ

### ISSUE THREAD

**Issue by y13i** [greymd/echo-meme#26]
template:[俺、{}（｀ェ´）ﾋﾟｬｰ]

**Comment by y13i** [comment]
[reference](https://dic.nicovideo.jp/a/%E4%BF%BA%E3%80%81%E4%BD%90%E8%97%A4%E8%A3%95%E4%B9%9F%28%60%E3%82%A7%CC%81%29%E3%83%94%E3%83%A3%E3%83%BC)

**Comment by greymd** [comment]
THIS COMMENT IS POSTED BY BOT -- [俺、{}（｀ェ´）ﾋﾟｬｰ] is imported. You rocked it!
