### ISSUE TITLE
new_meme_request:ともあれ、{}は滅ぶべきであると考える次第である

### ISSUE THREAD

**Issue by y13i** [greymd/echo-meme#27]
template:[ともあれ、{}は滅ぶべきであると考える次第である]

**Comment by y13i** [comment]
[reference](https://ja.wikipedia.org/wiki/%E3%82%AB%E3%83%AB%E3%82%BF%E3%82%B4%E6%BB%85%E3%81%B6%E3%81%B9%E3%81%97)

**Comment by greymd** [comment]
THIS COMMENT IS POSTED BY BOT -- [ともあれ、{}は滅ぶべきであると考える次第である] is imported. You rocked it!
