### ISSUE TITLE
new_meme_request:{}の怒りが有頂天になった　この怒りはしばらくおさまる事を知らない

### ISSUE THREAD

**Issue by y13i** [greymd/echo-meme#29]
template:[{}の怒りが有頂天になった　この怒りはしばらくおさまる事を知らない]

**Comment by greymd** [comment]
THIS COMMENT IS POSTED BY BOT -- [{}の怒りが有頂天になった　この怒りはしばらくおさまる事を知らない] is imported. You rocked it!
