### ISSUE TITLE
new_meme_request:「もうついたのか！」「はやい！」「きた！{}きた！」「メイン{}きた！」「これで勝つる！」

### ISSUE THREAD

**Issue by y13i** [greymd/echo-meme#31]
template:[「もうついたのか！」「はやい！」「きた！{}きた！」「メイン{}きた！」「これで勝つる！」]

**Comment by greymd** [comment]
THIS COMMENT IS POSTED BY BOT -- [「もうついたのか！」「はやい！」「きた！{}きた！」「メイン{}きた！」「これで勝つる！」] is imported. You rocked it!
