### ISSUE TITLE
new_meme_request:本当につよいやつは強さを口で説明したりはしないからな口で説明するくらいなら{}は牙をむくだろうな{}パンチングマシンで１００とか普通に出すし

### ISSUE THREAD

**Issue by y13i** [greymd/echo-meme#32]
template:[本当につよいやつは強さを口で説明したりはしないからな口で説明するくらいなら{}は牙をむくだろうな{}パンチングマシンで１００とか普通に出すし]

**Comment by greymd** [comment]
THIS COMMENT IS POSTED BY BOT -- [本当につよいやつは強さを口で説明したりはしないからな口で説明するくらいなら{}は牙をむくだろうな{}パンチングマシンで１００とか普通に出すし] is imported. You rocked it!
