### ISSUE TITLE
new_meme_request:溶鉱炉に沈んでいくシーン

### ISSUE THREAD

**Issue by 3socha** [greymd/echo-meme#50]
template:[{}よかった。特にラストシーンで{}が親指を立てながら溶鉱炉に沈んでいくシーンは涙無しには見られなかった。]

**Comment by greymd** [comment]
THIS COMMENT IS POSTED BY BOT -- [{}よかった。特にラストシーンで{}が親指を立てながら溶鉱炉に沈んでいくシーンは涙無しには見られなかった。] is imported. You rocked it!
